### ISSUE TITLE
rename start method to onSubscribe in Observer interface

### ISSUE THREAD

**Issue by SekibOmazic** [zenparsing/es-observable#103]
As far as I understand `start` method is (will be) invoked when the subscription is created (before first call to the `next` method). So `onSubscribe?(subscription: Subscription)` sounds more natural (to me at least).

Another issue is that `start?(subscription: Subscription)` is missing in the overloaded `subscribe`:
```Javascript
// Subscribes to the sequence with callbacks
    subscribe(onNext : Function,
              onError? : Function,
              onComplete? : Function) : Subscription;
```
and there is no way to use it in this case (https://github.com/zenparsing/es-observable/blob/master/src/Observable.js#L244-L251)

**Comment by RangerMauve** [comment]
Not sure about the `on` part of that name, since it's different from `next`, `error`, and `complete`.

**Comment by SekibOmazic** [comment]
Well it's the same dilemma for 
```javascript
subscribe(onNext : Function,
              onError? : Function,
              onComplete? : Function) : Subscription;
```
isn't it?
Naming is though business

**Comment by RangerMauve** [comment]
Well, in the case of the overloaded subscribe, the names don't really matter since they're just the names of the arguments internally, you could name the actual functions whatever you want. In the case of subscribe that takes an object, the names of the keys are all explicit. Maybe it would make sense to rename them all to use `on`? But AFAIK a lot of libraries already use the current convention so that might be a bit of a problem.

**Comment by SekibOmazic** [comment]
You're right, explicit names of the keys is valid point.

I wouldn't change names back to `on`. I think a lot of people got used to `next`, `error` and `complete` after migrating to RxJS5.

Renaming `start` to `onSubscribe` sounds appealing because it describes better what it is - a call back handler that is invoked at subscription time.
Hmm, maybe someone has better idea?

**Comment by RangerMauve** [comment]
Maybe `subscribed`?

**Comment by zenparsing** [comment]
@SekibOmazic Either all of the handlers should be "onX" or none of them.  We chose none, to make things more concise and javascripty. 

 `subscribed` is past tense, which is also inconsistent with the other handlers.

I'm not seeing a good argument for why "onSubscribed" or similar is better than "start".

The overload which takes the 3 functions is a shorthand for the common case, whereas "start" is a more advanced feature. Since it's a more advanced feature, it makes sense to have it available in the more advanced and general `subscribe` signature which takes an Observer object.

**Comment by SekibOmazic** [comment]
OK, I guess it's just a matter of "getting used to" the naming (like `start`)
