### ISSUE TITLE
Observable should be a thenable

### ISSUE THREAD

**Issue by jhusain** [zenparsing/es-observable#15]
This was an oversight. We should definitely spec this so that async await works on Observables out of the box.

the return value of the Observable will be come the resolution of the promise. Likewise errors become rejections.

**Comment by zenparsing** [comment]
I considered this, but was concerned that someone might want to actually deliver an observable asynchronously through a promise.  In other words, `Promise<Observable>`.  If we give observables a "then" method, then we effectively can't have `Promise<Observable>`.

```js
let promise = doSomethingAsync().then(_=> {
    return new Observable(sink => {
        sink.return(1);
    });
});

promise.then(x => console.log(x)); // "1", not an observable
```

I guess the question is, do we want to disallow `Promise<Observable>`, in exchange for directly working with async/await?

**Comment by stefanpenner** [comment]
@jhusain what is the fulfillment value of the `then`

**Comment by jhusain** [comment]
The value returned to the Generator's return method.

JH

**Comment by stefanpenner** [comment]
> The value returned to the Generator's return method.

sounds reasonable

**Comment by benjamingr** [comment]
Yes, when I suggested this in the composition functions thread we also considered a special symbol instead of making it a `then`able - so that should also be considered.

> I guess the question is, do we want to disallow Promise<Observable>, in exchange for directly working with async/await?

I can definitely think of situations where you'd want a `Promise<Observable>` but in all honesty those can be solved with `Promise<() => Observable>` which works pretty well.

**Comment by zenparsing** [comment]
Thinking out loud:  what if the subscription were either a "thenable" or a promise subclass?  If we allowed an empty argument list to "subscribe", we'd have:

```js
async function af() {
    let observable = getObservableFromSomewhere();
    let answer = await observable.subscribe();
    console.log(answer);
}
```

Thenable assimilation is kind of weird, so the suggestion would be making subscriptions a subclass of promise:

```js
class Subscription extends Promise {
    unsubscribe() : undefined;
}
```

Essentially a cancellable promise, with well-defined and reasonable semantics.  : )

**Comment by zenparsing** [comment]
If that suggestion works out, then it could potentially remove the need for a separate "forEach" and the need for me to think of a response to #20  : )

**Comment by domenic** [comment]
We'll hopefully be having full-on cancellable promises sooner rather than later (driven by fetch, so, I'm talking in terms of low-single-digit browser-releases). It might be reasonable to block observable unsubscription semantics until they ship.

**Comment by zenparsing** [comment]
@domenic are the conversations surrounding cancellation happening somewhere?  It would probably be a good idea for me to at least listen.

**Comment by domenic** [comment]
@zenparsing still booting up, maybe watch https://github.com/domenic/cancelable-promise but it's pretty empty right now.

**Comment by benjamingr** [comment]
@zenparsing the public conversation about cancellable promises got really noisy really fast. If you want to see an example of similar semantics you can see the bluebird 3.0 cancellation semantics - they're not the same but they're close: http://bluebirdjs.com/docs/api/cancellation.html 

If you're used to Rx semantics this is similar to `refCount`ed dispose.

Subscription as a thenable or a promise subclass sounds very reasonable - doesn't really matter which but I definitely see the merit in a subclass since it gets all the other useful methods as well as ones added to the API in the future.

**Comment by stefanpenner** [comment]
> Essentially a cancellable promise, with well-defined and reasonable semantics. : )

I think cancel and unsubscribe are different (although maybe overlapping)

To me,:

* `cancel` implies aborting the work that would otherwise realize the eventual value
* `unsubscribe` implies remove me as a follower.

`cancel` is actually much trickier to do safely then `unsubscribe`

For example, given:

```js
Promise.all([
  fetch('/user/1'),
  fetch('/user/2'),
  Promise.reject(new Error('...'))
])
```

We could augment `Promise.{all,race}` to `unsubscribe` from `fetch('/user/1')` and `fetch('/user/2')` as the final promise is detected to reject. This wouldn't cause `fetch` to be cancelled, but it would eagerly release.

**Comment by domenic** [comment]
This is going to turn into another promise cancellation thread, I can tell :(

**Comment by jhusain** [comment]
Agree with Stefan. Although I agree it would be a nice unification, Cancellation and unsubscription are semantically different from one another. They provide different guarantees.

JH

**Comment by zenparsing** [comment]
@jhusain What do you think about the general idea of making the subscription object thenable or a promise subclass, rather than the observable?

**Comment by benjamingr** [comment]
> This is going to turn into another promise cancellation thread, I can tell :(

Not a chance.

> Agree with Stefan. Although I agree it would be a nice unification, Cancellation and unsubscription are semantically different from one another. They provide different guarantees.

For what it's worth, some promise libraries have a notion of disposers (http://bluebirdjs.com/docs/api/resource-management.html). Observable dispose is in-between promise cancellation and promise dispose, with the big difference that an observable is lazy and disposing is done on the subscription itself.

@zenparsing 
> @jhusain What do you think about the general idea of making the subscription object thenable or a promise subclass, rather than the observable?

I think it would be very nice to be able to await an observable itself without needing a subscription, this might be a weak argument but if we force everyone to `.subscribe` it won't be fun for users. It's also entirely possible to do both (the observable is thenable and the subscription is a promise subclass).

It's also worth mentioning that if we're discussing async/await it might be nice to add semantics that allow hooking on a _single_ value basically acting like async iterators (that is, a `then`able .next for the next value of a subscription rather than the whole sequence) although backpressure issues arise.

**Comment by jhusain** [comment]
Agree with Benjamin that there is an ergonomic issue with awaiting an Observable by first calling subscribe. I hadn't considered the pain of this:

await obs.subscribe();

I think users will expect to await Observables directly as they do in .NET. I also think this expectation would be correct, because thening an Observable is a subscription. You're kicking off the side effects and waiting for the result. The tradeoff is that you cannot cancel as long as Promises remain uncancellable. However a future proposal manages to fix that then we'll have the best of all worlds.

JH

**Comment by zenparsing** [comment]
Do we normally we wouldn't think of "await" as kicking off side effects?

**Comment by domenic** [comment]
No, `await` does not kick off side effects normally. E.g. in `await doSomething()`, it's the `doSomething()` part that has side effects.

**Comment by benjamingr** [comment]
I think "kicking off the side effects" is probably better worded as "kick off the operation" in case of a lazy construct. As Domenic said when awaiting eager constructs (like promises) the `()` function call is what's calling the operation. You can `await p` for an existing promise which should not cause any side effects at all.

**Comment by domenic** [comment]
If observables were not lazy, then `await observable` would make sense. But assuming you want to keep them that way (i.e. as a function-class, see #11), then I think you need to do `await observable.subscribe()`, or perhaps better yet (again, #11) `await observable()`.

**Comment by benjamingr** [comment]
In essence both in `await promise` and `await observable` all that happens is a subscription is being added - the difference is that in the promise case that subscription forces the observable to start working since it's a lazy construct.

I'm not sure I understand what's the problem with `await observable` causing a side effect (where `await promise` does not). Are you arguing that the fact that an operation happens when you `await observable` in the background is confusing to developers or bad semantics?

**Comment by domenic** [comment]
I guess it seems like both to me. A type conversion (what happens when you do `await thenable`) should not cause side effects---bad semantics. And awaiting observables causing side effects while awaiting promises does not is confusing to developers.

**Comment by blesh** [comment]
Is it going to be clear that `await myObservable` cannot be cancelled?

it seems like adding this so observable can be used with `await` isn't a good idea, if it ends up being an anti-pattern when it's used. i.e. "Yes, you can use `await myObservable`, but you shouldn't because then you can't cancel it". Then again, this might be true for `for..on` syntax, and the `forEach()` method as well?

I *think* I'm with @domenic here in that you should have to call a method that returns a thennable object. Perhaps the subscription (generator) object that is returned from the `subscribe` method should be thennable. That way you can unsubscribe, and using `await` doesn't necessarily become an anti-pattern:

```
var subscription = myObservable.subscribe();
var returnValue = await subscription;
subscription.error('cancel with an error');
```

As I stated above, you could already use `Observable.prototype.forEach()` for the same thing, but I think using `forEach` is generally going to be bad practice, because of the lack of cancellation semantics.

**Comment by blesh** [comment]
I guess the shorter version of what I'm saying is: Encouraging use of Observable in any way that doesn't allow you to cancel it seems like encouraging bad practice.

I can totally be convinced otherwise, I guess.

**Comment by benjamingr** [comment]
That's an interesting point @blesh about cancellation.

There is a great deal of things you don't want to or need to cancel in server-side code, typically DB requests for example, or web requests (on the server, not the client) and so on.

In fact I've found that in the vast majority of the times I need cancellation I need concurrency anyway since the reason I'm cancelling is because what I need became irrelevant - in which case `await` isn't something I could use anyway.

(All that said, it's totally possible to do cancellation with await using `.return` which can in turn cancel the subscription it created - just have `then` return a cancellable promise - afaik those are the semantics anyway.)

-------

I also tend to agree with Domenic, we need to think of a way to make the syntax less confusing to people and still short - an `observable()` instead of `observable.subscribe()` would already be a big ergonomic improvement but as we noted we can't do that (not unless we have function classes, and given how Jafar coined that term a few threads away and there is no proposal yet - those are not coming to ES any time soon ;))

I think in the meantime awaiting subscriptions which become thenable or subclasses of promise is the best we can do right now. This also unifies forEach and subscribe.

**Comment by domenic** [comment]
> (not unless we have function classes, and given how Jafar coined that term a few threads away and there is no proposal yet - those are not coming to ES any time soon ;))

I think they are likely to come to ES exactly as fast as observable is likely to come to ES.

**Comment by stefanpenner** [comment]
> in which case await isn't something I could use anyway.

what about:

```js
try {
  let something = await somethingAwaitable;
} catch (e) {
  // cancel/unsubscribe somethingAvaitable ?
}
```

**Comment by benjamingr** [comment]
@stefanpenner 

```js
try {
  let something = await somethingAwaitable;
} catch (e) {
  // cancel/unsubscribe somethingAvaitable ?
}
```

I'm going to need a more concrete example to say how I would address it.

**Comment by stefanpenner** [comment]
@benjamingr sorry, i hit `comment` to quickly. Anyways, combining your comment, and @blesh's example leads to something interesting.

**Comment by blesh** [comment]
@stefanpenner right, but how do I manually cancel an Observable that is being used with `await`? If I'm awaiting some AJAX call, and I"m about to change my view to something that doesn't care about it, what do I do if I've used `await`?

The code example I gave above is bad, as it would *never* hit the subscription.error() call... it should be more like:

````js
async function oneWeirdTrick(subscription) {
  try {
     var returnValue = await subscription;
  } catch(err) {
     // do something with err
  }
  return returnValue;
}

let subscription = myObservable.subscribe();

oneWeirdTrick(subscription);

subscription.error('cancel with an error');
```

**Comment by stefanpenner** [comment]
> @stefanpenner right, but how do I manually cancel an Observable that is being used with await? If I'm awaiting some AJAX call, and I"m about to change my view to something that doesn't care about it, what do I do if I've used await?

@blesh I think I need a real example, where both await and cancellation are used together.

**Comment by blesh** [comment]
A real example would be where you have an AJAX request wrapped in an observable, you kick if off when you're loading your view in a client-side app, then the user navigates to another view before the observable returns, and you want to cancel the observable. In that case, using `myObservable.forEach()` or `await myObservable` would be bad, because they're not at all cancellable. The only way you can get cancellation magic is with `subscribe` or `@@observe`.

Another would be the typical "autocomplete" text box, where you're getting some search results based on the last value entered, if the user hits a new key in the text box before the previous query returns, you want to cancel the previous query and await the next one.

**Comment by benjamingr** [comment]
In concurrent cases and combinations `await` shouldn't be used (the autocomplete example), await is only for sequencing things one after the other. I'm all for a `flatMapLatest` and I'm not sure how this can be expressed without clever combinators (or implementing them) - let alone with await.

As for ajax wrapped request - if the `then`able returned from an observer is cancellable, the async function will call cancel on it when it is itself cancelled (I think?) in which case the loading-your-view example will work.

**Comment by blesh** [comment]
@benjamingr @stefanpenner  to clarify, I'm making the case that:

```js
await myObservable;
```

...is not cancellable, because I've gotten no reference to anything I can call `return()` or `error()` on to cancel the subscription it creates.

Therefor, I think it is more desirable that whatever is returned from `subscribe` be "then-able". Likewise, I think whatever is returned from `forEach` should be cancellable (and perhaps the same thing?).

**Comment by domenic** [comment]
I agree cancelable promises are an important building block here.

> (and perhaps the same thing?).

Yes, currently this proposal contains three methods all of which basically do the same thing (subscribe, [Symbol.observer], and forEach). In general any argument that applies to one of them applies to all. Although there is probably some room for trimming the fat.

**Comment by blesh** [comment]
@domenic but is it a cancellable promise or a then-able subscription that is necessary here? I'd argue the latter, since having a `next()` method on the returned type also has value.

**Comment by domenic** [comment]
Having a `next()` method on the return type is explicitly not part of this proposal (and never was).

**Comment by benjamingr** [comment]
> Therefor, I think it is more desirable that whatever is returned from subscribe be "then-able". Likewise, I think whatever is returned from forEach should be cancellable (and perhaps the same thing?).

I think you should be able to `.then` `.subscribe`, the question is whether or not you should also be able to `.then` the observable itself is what we're discussing at the moment. Mainly, whether or not if not having to type `.subscribe()` over and over is worth not being 100% logically correct, or being confusing to JavaScript developers (see Dom's points above).

> ...is not cancellable, because I've gotten no reference to anything I can call return() or error() on to cancel the subscription it creates.

You're not the one that is cancelling it though, when the async function gets cancelled the inner `then`able gets cancelled too which would in turn unsubscribe from the observable.

**Comment by blesh** [comment]
@domenic ... ah, you're right it was never part of *this* proposal. I keep getting this confused with the [original spec](https://github.com/jhusain/observable-spec) that this was modeled after, in which `subscribe` returned a generator.

**Comment by zenparsing** [comment]
@blesh We'll get that repo updated soon.

**Comment by jhusain** [comment]
It's worth mentioning that await has never guaranteed no side effects. Promise.resolve calls "then" on non-Promises and there's nothing about the thenable contract that guarantees no side-effects. I think developers think about await in terms of sequencing ("then" is pretty appropriate here). The definition of "then" as a subscribe on an Observable seems pretty intuitive to me. It's worth pointing out that in .NET you can await an Observable. Developers seem to be able to intuit the behavior.

JH

**Comment by domenic** [comment]
> It's worth mentioning that await has never guaranteed no side effects.

Agreed.

> there's nothing about the thenable contract that guarantees no side-effects.

Strongly disagree. The thenable contract is about type conversion between promise implementations, and fulfilling that contract means behaving like a promise---i.e. no side effects. It's true that Promises/A+ is phrased in terms of "you must do this" and not "you must do this and nothing else." But everyone would agree that "perform the usual Promises/A+ steps and then delete your C:\ drive" is not really fulfilling the thenable contract. Similarly, "perform an arbitrary action, then create something that performs the usual Promises/A+ steps" is not in the spirit of the contract either.

**Comment by blesh** [comment]
> The thenable contract is about type conversion between promise implementations, and fulfilling that contract means behaving like a promise---i.e. no side effects.

@domenic (This is an honest question, I can't think if a better way to phrase it, sorry, don't read into it) How can a *contract* enforce no side-effects in JavaScript?

**Comment by stefanpenner** [comment]
> How can a contract enforce no side-effects in JavaScript?

it can't strictly enforce, rather by convention it can be enforced.

**Comment by blesh** [comment]
Ah... I guess when I read "guarantee" I think "enforcement".

**Comment by jhusain** [comment]
Regardless of the original intent of the original spec, we should
realistically discuss what potential hazard implicit Observable/Promise
might create. I fail to see what hazard is prevented by disallowing
stateful Observable/Promise adaptation when the side-effects will just end
up being executed immediately prior to an await. Forcing someone to call
await on an observable.subscribe() that promptly deletes their hard drive
doesn't seem like an improvement to me over simply executing the
side-effects during adaptation.  I also want to preserve the ability to
await something lazy.

I think we should be focused on giving developers what they expect. We have
some evidence that they expect this implicit conversion from the .NET
platform where async/await has been vetted.

**Comment by domenic** [comment]
I've covered what the hazard is above:

> A type conversion (what happens when you do await thenable) should not cause side effects---bad semantics. And awaiting observables causing side effects while awaiting promises does not is confusing to developers.

> I think we should be focused on giving developers what they expect.

I definitely agree. Which is why I think awaiting anything should not cause side effects, since that is what _JavaScript_ developers will expect from using promises.

**Comment by jhusain** [comment]
JavaScript developers are using Promises, and presumably in this situation
they will also be using Observables. Is it not reasonable for them to
understand the semantics of the type they are using on the right-hand-side
of an await expression? If we assume no knowledge of Observable semantics,
the state hazard presents itself regardless of whether developers use await
or subscribe. If devs don't know Observables were stateful they could
inadvertently repeat side-effects by calling subscribe twice. Your argument
seems predicated on the idea that developers will only understand await in
terms of Promises, but if we make it work on Observables out-of-the-box,
why would that be so?

In a world in which await worked on both Promises and Observables, why
would developers assume await enforces Promise semantics? Why wouldn't they
assume it does strictly what it says: "await"? I'm concerned that it is
short-sighted to to limit the concept of "waiting" to Promises when we
might have another async type in the language.

Seems we are repeating our arguments, so let me propose a compromise that
might make everyone unhappy: returnValue(). This combinator would return a
Promise which would hopefully remove all ambiguities.

**Comment by jhusain** [comment]
@domenic any objection to observable.returnValue()? Would like to have some solution for async/await integration before Babel inclusion.

**Comment by benjamingr** [comment]
If it's `.returnValue` it might as well be `toPromise` and describe what it is doing - it's also less to type.

**Comment by zenparsing** [comment]
@jhusain wouldn't returnValue() be equivalent to subscribe(), (with zero arguments) if the returned subscription were promise-y?

**Comment by benjamingr** [comment]
@zenparsing that would require `.subscribe` to allow being called with 0 arguments, I was not aware this is the case at the moment.

**Comment by zenparsing** [comment]
@benjamingr it's not the case at the moment, but we could certainly allow that if we wanted to.

**Comment by jhusain** [comment]
Commented in other thread about hazard of making subscribe a promise. The reason to call it final value is that there is likely to be other combinators along the same lines: firstValue(), lastValue(), and so on.

**Comment by domenic** [comment]
My objection to .returnValue() is that we are adding a fourth almost-does-the-same-thing method. I would much prefer the direction discussed in https://github.com/zenparsing/es-observable/issues/20#issuecomment-108085880 to pare things down to one method instead of adding a fourth.

**Comment by benjamingr** [comment]
@zenparsing could you clarify what was settled on here? How are subscriptions going to be awaited?

**Comment by blesh** [comment]
@benjamingr agreed, I'm actually a little confused about this. Last I talked to @jhusain he had said `when` as opposed to `then`, at least for the `RxJS vNext` library.
