### ISSUE TITLE
Compliance test suite

### ISSUE THREAD

**Issue by chadhietala** [zenparsing/es-observable#28]
Would be really cool if this could be published to NPM with a full compliance test suite so that framework authors and others could develop some more userland implementations besides RXJS and Bacon. I think this is important to converge on the a shared understanding of the primitive. The [Promises A+ compliance suite](https://www.npmjs.com/package/promises-aplus-tests-phantom) is a good example of this.

**Comment by blesh** [comment]
This has been discussed in the past at http://github.com/reactive-streams/reactive-streams-js ... But the discussion was put on hold pending the finalization of this spec. While building the next version of RxJS together, such tests will undoubtedly be created. Perhaps we can extract those to something more universal? 

cc/ @briancavalier @mattpodwysocki

**Comment by benjamingr** [comment]
@chadhietala in order to do that you first need a spec that describes how observables from different libraries interact with each other. In Promises/A+ the libraries share an API.

**Comment by blesh** [comment]
An *interop-only* compliance suite might be useful. Not necessarily "is it an Observable?" but more "can I observe it?"

- Does it have `[Symbol.observable]`?
- Does what it returns from `[Symbol.observable]` have a `subscribe` method?
  - that returns an object with an `unsubscribe` method?

I think at the end of the day, this gets tricky because there is a lot more depth to possible implementations of Observable-like-things than there are for Promise.

**Comment by hollowdoor** [comment]
@benjamingr A pipe method. ;)

**Comment by benjamingr** [comment]
@blesh has a conclusion been reached on what consists of an observable?

**Comment by hollowdoor** [comment]
@benjamingr I'd like to know this too.

It's too bad it's not as easy as:
```javascript
if(typeof looksLikeAPromise.then === 'function'){
    //Good enough
    promise = Promise.resolve(looksLikeAPromise);
}
```

Maybe a test for a `from` method?

I still think observables are enough like streams we should just be able to **pipe** them.

**Comment by zenparsing** [comment]
@hollowdoor 

If you want to duck-type-test, you can use the same strategies that you might use for iterators:

For iterators:

```js
// Testing for a next method
if (typeof obj.next === "function") ;

// Testing for Symbol.iterator
if (typeof obj[Symbol.iterator] === "function") ;
```

Similarly, for observables:

```js
// Testing for a subscribe method
if (typeof obj.subscribe === "function") ;

// Testing for Symbol.observable
if (typeof obj[Symbol.observable] === "function") ;
```

The choice of whether to test using "subscribe" or "Symbol.observable" would depend on the situation.

**Comment by hollowdoor** [comment]
@zenparsing That is what I've been doing.

I'm more interested in how two observables might be composed together.

With streams we just:
```
readable.pipe(writeable);
```

I was considering the from method because it is a composition method even though it's for transforming iterables.

But this is not about a test suit. Maybe I'll take this to another issue one of these days.

**Comment by RangerMauve** [comment]
@hollowdoor Observables don't take an input the way pipes do. They keep track of the source of their events internally. What you'd be more likely to do is `map` over the observable to produce a new observable with the given transformations. Instead of piping observables into other observables, you'd be passing them into something that would subscribe and optionally return a new observable.

**Comment by hollowdoor** [comment]
@RangerMauve Subscribers take input. Would a duplex behavior be out of line for an Observable? Where the Observable is also a Subscriber? Operating on values sent by a source Observable then passing on new values to other Subscribers.

Maybe a combined Interable Observable:
```
{
    subscribe: function(){
         //This shouldn't be called from host observables.
         //Made into a noop when passed to subscribe of another observable.
         //But subscribe is not chain-able like a pipe. Maybe it should be.
    },
    next: function(value){
        //The host emits the value to "this" Observerable somehow.
    },
    error: function(){},
    complete: function(){}
}
```

This is pretty much the same thing as map, but no callback needed in user space.

Observable.subscribe would be where the decision to return the current, or the Subscriber depending on if the Subscriber is also observable.

Observable.from already kind of does this, but it's not an instance method that would delegate from a host observable.

**Comment by RangerMauve** [comment]
@hollowdoor I'm not too sure about observables being subscribes. I guess if it's OK for a subscriber to subscribe to multiple sources, then somebody could probably make a library that would facilitate that. I'm not too sure that it should be considered as part of the spec, though.

**Comment by hollowdoor** [comment]
@RangerMauve Yeah. I was thinking about a different method than subscribe though. I just used subscribe to get the point across. Another specific method would better. Like `from` but used only on another subscriber that's also an observable.

I don't know if it should be in the spec either, but I put the idea out there to see what you think. If I didn't and the idea is the best in the world we missed an opportunity. If it's the worst then it's just an idea waiting to be put in an overzealous library.

**Comment by zenparsing** [comment]
Tests are published to NPM under `es-observable-tests`
