### ISSUE TITLE
[Symbol.observer] is unergonomic for people that know what they're doing.

### ISSUE THREAD

**Issue by blesh** [zenparsing/es-observable#37]
Observable is a functional programming thing. In pure functional programming, there should be no "Zalgo". So anyone that is using Observable *properly* will want to always use `[Symbol.observer]()` to subscribe to the observable. I think it's safe to say that I know exactly zero heavy users of Observable, at Netflix at least, that *want* to do this. (I'll go so far as to say that list probably includes @jhusain. haha) Just playing with it hurts and I find myself wanting to override the whole thing like: `Observable.prototype.subscribe = Observable.prototype[Symbol.observer]` just to enjoy using the type.

I understand that Zalgo is a footgun for people who are coding imperatively, so we need to build libraries around this defensively. I guess I feel hiding it under `[Symbol.observer]` is just a little too much. 

I'd like to propose that `[Symbol.observer]` change to either:

- `subscribe` - back to the good old days of RxJS, maybe make the "safe" version be named `when`.
- `forEach` - because the name alone makes it sound like sync behavior, honestly.
- `observe` - because it's less annoying to type over and over than `[Symbol.observer]`.

At some point people are going to have to put on their big-boy pants about Zalgo. If you're programming functionally, it's really all or nothing, or you better know what you're doing. Observables are not promises. They're not a stateful construct for async imperative programming, they're a functional programming paradigm.

**Comment by blesh** [comment]
To be clear, I see the value of a Symbol method for interop, so I think there *should* be a Symbol method, but I don't like `subscribe` being async by default now that I'm using this design a bit.

**Comment by domenic** [comment]
I continue to assert that this proposal will be blocked in TC39 if it provides any synchronous subscription mechanisms at all.

**Comment by zenparsing** [comment]
I agree that Symbol.observer is quite unergonomic.  In fact, I've made the point before that because of the ergonomics, users will tend to reach for "subscribe" anyway.

We know that there is strong support for async subscription; it will certainly be a central to the core API.  What we haven't yet seen is a truly compelling use case for synchronous subscription.

**Comment by jhusain** [comment]
My recollection is that @wycats had a good use case for synchronous subscription. He was interested in using Observable and iterator together to model epoll. The goal is to notify consumers that information is available, but delay the potentially expensive process of retrieving the information until the consumer explicitly indicates that they need it. Value generation is handled via the iterator (pull), but the consumer is alerted there is a new value by the Observable (push). This push/pull interplay is ideal for APIs like epoll. It also has applications in Model/View synchronization a la O.O.

If the Observable can only notify asynchronously, it means that data could be lost if several values become available in the same job. However the consumer would not get the opportunity to retrieve all values because by the time they received the notification asynchronously, earlier values would no longer be available via the pull mechanism. Conversely if the notifications could arrive synchronously, the consumer could retrieve them via a pull immediately with no risk of data loss.

**Comment by benjamingr** [comment]
> So anyone that is using Observable properly will want to always use `[Symbol.observer]()` to subscribe to the observable. I think it's safe to say that I know exactly zero heavy users of Observable, at Netflix at least, that want to do this.

As an observable user, this is true for me _based on performance_, in RxJS and other observable libraries async subscription is slow because paths that are already async aren't detected by the library and it has to use the trampoline and an async scheduler. This is not true for example for some promise libraries which reach close-to-parity with sync scheduling in realistic use cases. 

If native observables are implemented well enough I will definitely use `.subscribe` and not `[Symbol.observer]()`. 

> > I find myself wanting to override the whole thing like: `Observable.prototype.subscribe = Observable.prototype[Symbol.observer]` just to enjoy using the type.

Would you mind elaborating why? Use cases demonstrating pain points would go a _long_ way here. If you're using pure functional programming there shouldn't be any difference between sync and async subscription since it's unpure mutable state - so why would it be painful to use?  

>  If you're programming functionally, it's really all or nothing, or you better know what you're doing.

This is an extremely harmful statement to make IMO. Asserting there are _real_ programmers who _don't make concurrency mistakes_ and there are "little boy" programmers who "don't get" functional programming is harmful and counterproductive. 

> Observables are not promises. They're not a stateful construct for async imperative programming, they're a functional programming paradigm.

True (neither are promises), but irrelevant. The fact a construct is "functional" is orthogonal to "people are going to shoot themselves in the foot with it".

**Comment by zenparsing** [comment]
@jhusain As long as the observable can notify (send "next" values) synchronously, then it seems this use case is covered.  Maybe I'm misunderstanding something though.

I'm imaging that you have one observable that represents a notification that there is something to be processed.  The consumer of that observable receives the notification, then pulls data out of the buffer synchronously with an iterator.  The fact that subscription is async doesn't seem to matter, because that scheduling is just applied once at subscription time.

**Comment by jhusain** [comment]
Should've tagged @domenic in my reply. earlier in the thread he says that he asserts that any synchronous subscription to mechanism will cause Observable to be blocked in TC-39.  I also thought of another reason for sync subscription: modeling DOM events. My understanding is that DOM events do not guarantee async notification.

**Comment by benjamingr** [comment]
>  My understanding is that DOM events do not guarantee async notification.

That is true, but that is not something people working on the DOM like. In fact, many people would enjoy it very much if stronger concurrency guarantees would be laid down by future DOM APIs.

Bugs caused by sync subscription race timing are pretty terrible. This is why I believe many people in the TC like @domenic feel strongly about them, and this is why I feel strongly about them too. 

That said - I'm all ears for any argument that is not "performance" and I'm all ears for any _based in facts_ argument that shows theoretical performance issues can't be solved (assuming it takes the trampoline, and async tagging into consideration).

**Comment by zenparsing** [comment]
@jhusain Thanks - the DOM thing got my mind going.  I'll need a bit more time to gather my thoughts on it though.

**Comment by jhusain** [comment]
Modeling EventTarget is one of the core goals of this proposal.
Unfortunately an event target may require a response synchronously (ex.
preventDefault). Under the circumstances it would seem that any abstraction
that could force the first notification onto the next job is unable to
fully model EventTarget. @domenic do you have any ideas about how to solve
this problem?

The push/pull epoll scenario also seems valid. It's not clear to me how we
make that work without an unbounded buffer, which is not acceptable for IO.
Incidentally I believe the combination of the observable and generator was
@bterlson 's idea so I'll tag him here as well.

Rather than preclude these use cases I like our approach of obscurity. My
expectation is that consumers will overwhelmingly use the subscribe method
which will allow them to maintain their invariants. The number of producers
(creators of observable classes) are far fewer, and are likely to be a
pretty sophisticated. This group is  much better equipped to understand the
nuances of how to guard against reentrancy.

Let's not forget that we also have a valuable resource in babel to
experiment and see if consumers finding and using synchronous subscription
is actually a problem in practice. At the moment we don't have any
experience that we can use to evaluate how well the obscurity strategy will
work. Potential hazards have to be evaluated against the risk they will be
encountered in practice. Without that data point it seems to me that
blocking the proposal on this issue would be premature.

On Jul 5, 2015 7:24 PM, "zenparsing" <notifications@github.com> wrote:
>
> @jhusain Thanks - the DOM thing got my mind going. I'll need a bit more
time to gather my thoughts on it though.

**Comment by benjamingr** [comment]
> Modeling EventTarget is one of the core goals of this proposal.
Unfortunately an event target may require a response synchronously (ex.
preventDefault).

Interesting, would you mind writing a snippet of behavior we can't model with async subscription we can play around with? 

> The push/pull epoll scenario also seems valid. It's not clear to me how we
make that work without an unbounded buffer, which is not acceptable for IO.

That's right, in general in scenarios where `.next()` is called synchronously an unbounded number of times the only way we can handle that is an unbounded buffer - that would be unacceptable for C# for example. Can you show a convincing case or code snippet we can discuss on why that'd be problematic for JavaScript? (Where `next` is called synchronously an unbounded amount of times, preferably one where the problem does not exist in current APIs anyway). 

> My expectation is that consumers will overwhelmingly use the subscribe method
which will allow them to maintain their invariants. The number of producers
(creators of observable classes) are far fewer, and are likely to be a
pretty sophisticated. This group is  much better equipped to understand the
nuances of how to guard against reentrancy.

My anecdotal advice from promises is while people are quick to adopt they tend to make mistakes regarding how they use the API. I can totally see a question on Stack Overflow where someone is complaining about "returning from an observable" and someone else answering "use `[Symbol.observer]`". Assuming people will understand the abstraction and will avoid [explicit construction](http://stackoverflow.com/questions/23803743/what-is-the-explicit-promise-construction-antipattern-and-how-do-i-avoid-it) is not something I think we should lightly do. 

>  At the moment we don't have any experience that we can use to evaluate how well the obscurity strategy will work. Potential hazards have to be evaluated against the risk they will be encountered in practice. 

Well, as an anecdotal data point `XMLHttpRequest` defaults to performing an async request but people abuse it to perform synchronous XHR all the time. I'm worried that if "discovered" this could be an issue. I don't think a feature being risky is alone a reason to not include it if it has important and valuable use cases - which is why I asked for code demonstrating the said use cases above. 

> Without that data point it seems to me that blocking the proposal on this issue would be premature.

Agreed, I think that a convincing (and not contrived) use case would go a long way for synchronous subscription.

**Comment by benjamingr** [comment]
I'll open a separate issue.

**Comment by blesh** [comment]
@benjamingr 

> Would you mind elaborating why? Use cases demonstrating pain points would go a long way here.

As I stated in the other issue, if you're programming purely functionally, it becomes wasteful to schedule every single subscription, instead you're going to want to call Symbol.observer every single time. If you find yourself needing to use the async subscribe, you're doing something wrong.

**Comment by blesh** [comment]
This seems to be solved, as it was removed? Closing.
