### ISSUE TITLE
BehaviorSubject based on es-observable (newbie question)

### ISSUE THREAD

**Issue by pkese** [zenparsing/es-observable#64]
Can someone please help me figure out what would be a reasonable implementation of Rx-style `BehaviorSubject` functionality based on es-observable?

**Comment by blesh** [comment]
Any subject would really be a standalone class that would either duck-type as an observable, or subclass it and completely override it's `subscribe` and `forEach` methods, as well as add methods for the `Observer` interface.

This is because all Subjects have a underlying array of observers they emit to, and calling `subscribe` or `forEach` on them adds to the internal observers list.

`BehaviorSubject` is just a specialization of that pattern.

**Comment by pkese** [comment]
Thanks
