### ISSUE TITLE
Conversion to async iterator with backpressure

### ISSUE THREAD

**Issue by zenparsing** [zenparsing/es-observable#74]
It's possible, using this protocol, to convert an observable to an async iterator while transmitting backpressure toward the observable source using promises.

Here's the sketch:

```js
class Observable {
    
    async *[Symbol.asyncIterator]() {

        let queue = [], resolveNext = null;

        function send(type, value) {

            // This promise is resolved once the completion has been transmitted to the "puller"
            return new Promise(resolve => {

                let rec = { type, value, resolve };

                if (resolveNext) {
                    
                    resolveNext(rec);
                    resolveNext = null;
                    
                } else {

                    queue.push(rec);
                }
            });
        }

        function next() {

            if (queue.length > 0) {
                
                let rec = queue.shift();
                rec.resolve();
                return rec;
            }

            // Assert: resolveNext is null
            return new Promise(r => resolveNext = r);
        }

        let subscription = this.subscribe({

            next(value) { return send("normal", value) },
            error(value) { return send("throw", value) },
            complete(value) { return send("return", value) },
        });

        try {

            while (true) {

                let { type, value } = await next();

                if (type === "return") return value;
                else if (type === "throw") throw value;
                else yield value;
            }

        } finally {

            subscription.unsubscribe();
        }
    }
    
}
```

**Comment by domenic** [comment]
This is building an ad-hoc protocol on top of observables though, right? Where you assume the creator of the observable interprets the return values from the observer's methods in a certain way? It doesn't actually give you backpressure in any general sense; it's just plumbing for allowing you to handle your own backpressure.

**Comment by benjamingr** [comment]
I'm sorry but I don't understand what the above code example is supposed to illustrate. A few lines of example usage would go a long way.

**Comment by zenparsing** [comment]
Sorry, this was just something of a note to myself for later.  I'm not proposing that anything be added to the design.  I just wanted to see if it was possible to transmit backpressure toward the source using the current protocol.

@domenic yeah, that's right.  A better approach to backpressure is just to use async iterators/generators  to begin with.  : )

@benjamingr Something like this:

```js
// A "backpressure-aware" observable
let observable = new Observable(sink => {
    (async _=> {
        await sink.next(1);
        await sink.next(2);
        await sink.complete();
    })();
});

// Consuming the "backpressure-aware" observable with for-await
async function f() {
    for await (let x of observable) {
        await somethingLongish();
    }
}
```

**Comment by blesh** [comment]
So.. in this world, you'd have all Observables handle backpressure by allocating a promise for each `next`, `error` or `complete` event? Sounds expensive.

The RxJava-style observable with backpressure control is probably a cleaner and more performant way to handle this. In that model, on subscription you request a certain number of values from the producer, which then pushes that number of values at you before you need to request more. (basically).

There was talk of building RxJS 5 like that, but it's not quite as performant as the plain Observable, and frankly, even @benjchristensen came to the conclusion that that type wasn't really just an "Observable", but a "Flowable" as he called it, because it has push/pull semantics rather than just push semantics.

There was/is still even discussion of building a RxFlowable library separately from RxJS, because they solve two different problems. The Flowable type was more useful for node and I/O type use cases and less useful for web UI work. At least that was the consensus during the discussions.

**Comment by zenparsing** [comment]
Sigh, more anti-promise party line...

Closing this, it was merely a sketch for posterity

**Comment by blesh** [comment]
@zenparsing ... sorry, I was confused by the code above, it looked like you were going to have all Observers return promises. Rather you were leveraging the return value of next and returning a Promise through that.

I think RxJS 5 still has next, error and complete returning `void`. We haven't hit any real use-cases for returning a value from those, nor have we any use cases for the return value passed to `complete`.
