### ISSUE TITLE
Observable.throw?

### ISSUE THREAD

**Issue by blesh** [zenparsing/es-observable#86]
While `Observable.of` is used to create a set of successful values, Their isn't a mechanism for creating an erred observable in this spec.  An `Observable.throw` would fit this need. It dovetails with promise functionality too.  `Promise.resolve` -> `Observable.of`, `Promise.reject` -> `Observable.throw`.

Seems like a small addition, but I'd like to read your thoughts.

**Comment by benjamingr** [comment]
Can you show some compelling examples of usage?

**Comment by staltz** [comment]
```js
var result = Observable.of('a', 'b', 17, 'c')
  .flatMap(x => {
    if (typeof x === 'string') {
      return Observable.of(x + 1, x + 2, x + 3);
    } else {
      return Observable.throw(new Error('should have been a string'));
    }
  });
```

**Comment by benjamingr** [comment]
@staltz sorry but you'll have to work a little harder than that. If `flatMap` isn't in the ES standard it's hard to justify `.throw` using it as an example.

**Comment by staltz** [comment]
Why have `Observable.of` then?

**Comment by benjamingr** [comment]
@staltz the goal at this point (if I understand it correctly) is to add observables to the language so they can be used as interop targets for APIs and then add the nice combinators (map/filter/flatMap/combineLatest etc) at a separate later proposal). 

This is to make this proposal less objectionable and to to postpone bikeshedding which will happen about every operator we discuss anyway. That way, people will be able to use RxJS to consume native APIs easily.

We can get `Observable.of` because we have `Array.of`, we can get `Observable.from` because we have `Array.from`. I don't really understand the logic of that in particular since Arrays and observables are nothing alike (sans the fact arrays are iterable and observables can be made to dual iterables). Also since part of what's blocking `Observable#map` is the fact there is no `Iterable#map` in the language. 

I think @zenparsing or @jhusain can probably shed more light on `Observable.of` making it into this spec in the first place. 

Anyway, I think `map/filter/flatMap` are much more fundamental than `.throw` or `.of` to being able to use observables ergonomically. I'm for whatever option helps the spec move forward at this point.

**Comment by blesh** [comment]
> I'd like to read your thoughts.

I haven't commented since, because I'm READING YOUR MINDS. :)

No, this is a good discussion. I wanted to bring it up because it seems to dove tail with `Promise.reject`... whose usefulness is also dubious I suppose. Perhaps @domenic can provide more context to why we have `Promise.reject`? Perhaps the use cases are similar, perhaps they're not.

**Comment by benjamingr** [comment]
@blesh as a user of both observables and promises - I use `Promise.reject` a lot more than I use `Observable.throw`. I can easily come up with 5-10 useful use cases for `.throw`, often because it is very uncommon and discouraged to `throw` from promise returning functions (Zalgo something something) so you'd return rejections instead. 

Also note that promises didn't ship with some important features (ahem cancellation ahem finally) in ES2015 so I doubt we can make an argument here about that.

That said, if we use observables for singular items I can easily come up with cases - the easiest one being avoiding having two error channels:

```js
function get(url) {
    if(typeof url !== "string") return O.throw(new Error("Invalid URL Parameter"));
    var s = new Subject();
    var xhr = new XMLHttpRequest;
    xhr.onload = () => { s.next(xhr.responseText); s.complete(); };
    xhr.onerror = (e) => { s.error(e); };
    xhr.open("GET", url);
    xhr.send();
    return s; 
}
```

Of course, the example isn't great (I wouldn't use a subject here, I don't deal with cancellation etc) but it illustrates how `.throw` is useful. If I didn't use `.throw` the consumer of the API would have to handle both regular exceptions and observable errors - now they only have to deal with one kind.

**Comment by zenparsing** [comment]
I don't want to go here at this point in time.  If we add `Observable.throw`, then do we need `Observable.complete`?  : )

**Comment by ljharb** [comment]
Yes, just like Promise.resolve and Promise.reject.

Please do not underestimate how important API symmetry is to some of us on the committee. To my mind, Promise and Observable are quite related. Just my 2¢

**Comment by blesh** [comment]
> do we need Observable.complete

Not if you get rid of that crazy argument. :P haha

**Comment by staltz** [comment]
`Observable.complete` ? That's `Observable.empty()`, and yes, it's very useful. Use case would be similar to what I already showed, in flatMap etc.

**Comment by benjamingr** [comment]
I don't think we need `Observable.empty` if we have `.from` in the spec although it's useful and I use it a lot.
