### ISSUE TITLE
Revisit unicast vs. multicast

### ISSUE THREAD

**Issue by benjamingr** [zenparsing/es-observable#93]
Given http://staltz.com/why-we-built-xstream.html I think it would be cool if @staltz could argue his case for why hot observables are more suitable to user applications than cold ones for the web platform.

(If that is note the case, let this issue serve as documentation for this discussion)

**Comment by blesh** [comment]
You can compose hot observables from cold, but not the other way around. Hot, multicast observables have internal state, cold do not. One is just a function, possibly pure. The other is a function with side effects that closes over state.

Hot by default observables as a primitive aren't as useful.

Hot by default observables as a higher level abstraction for a framework are totally fine.

**Comment by staltz** [comment]
> Hot by default observables as a higher level abstraction for a framework are totally fine.

Yep, that's why. I'm still an "RxJS guy" when it comes to reactive programming outside the fences of a framework. Also, I find it convenient that once people learn xstream, I can just tell them RxJS Observables are essentially xstream Producers with operators.

> I think it would be cool if @staltz could argue his case for why hot observables are more suitable to user applications than cold ones for the web platform.

I didn't say hot is more suitable for UI, I said hot is more suitable for applications that have very few `subscribe` invocations relative to the size of the Observable graph.

**Comment by benjamingr** [comment]
Great, this is what I was hoping to hear. Thanks.
